### ISSUE TITLE
Running live does not wait for Initialize

### ISSUE THREAD

**Issue by TimErps** [stefangolas/PyLynx#2]
When running live (not simulation) you run into an "Application blocked" error as it does not stop to wait for the instrument to initialize. This causes the Python to abort operation. Modifying/copying the wait_for_simulation into a wait_for_initialize function allows for a pause to be added to wait for state 129, which indicates the unit is initialized and the code waits until the unit is ready to run code. In that case, the run completes successfully and the Lynx runs the corresponding code successfully. 

Thanks again for getting our Lynx moving using Python!

**Comment by stefangolas** [comment]
Added a hardware initialization wait loop to LynxInterface.setup (line 291 in mm4_cmd). I think the code I'm looking for is 5, but I can't test it on my end without a machine. Feel free to close the issue if this works. 

`    def wait_for_hardware_initialize(self):
        initialized = False
        while not initialized:
            r = self.get_application_state()
            initialized = r['ApplicationState'] == 5
            time.sleep(1)
`

**Comment by TimErps** [comment]
We might want to get someone from Dynamic Devices to verify what the actual states are, because I know wait for Simulate also doesn't work if its on the instrument connected software, and the instrument is initialized, as that returns state 131 on my instrument, so it just never triggers to start the simulation. I'm assuming there's probably a significant amount of states that just convey a small amount of information. The 129 may be because the system I'm testing it on is two arm, so maybe there's some additional information encoded in that number versus the 5?

I can test if the patch works on my instrument tomorrow for you

**Comment by stefangolas** [comment]
There's definitely a difference between our MM applications because I only have single-digit states. Could you share the output log where it shows the response codes?

My methodology for figuring out which response code corresponds to which state is running a Python script that continually runs get_application_state and then I'll experiment with flipping between states and see what comes out.

**Comment by TimErps** [comment]
Here's the log of a run I ran this morning. Ours goes from 33, to 129 (ready to run?), to 133 (robot is moving)

[PILynx_2023-08-28_030445.log](https://github.com/stefangolas/PyLynx/files/12457597/PILynx_2023-08-28_030445.log)

**Comment by TimErps** [comment]
I thought it might have something to do with our software configuration, so I tried disabling both Snapshot Recovery, and Concurrent operations, however neither have changed what Status the Lynx is outputting. Similarly we run into issues when the system is initialized and I want to simulate something, as that returns status 131.

**Comment by stefangolas** [comment]
Ok that makes sense. I imagine it's just an MM4 version issue. I will push an update that can handle both sets of response codes.

**Comment by stefangolas** [comment]
@TimErps I think the latest commit fixes your problem.

simulation_mode = r['ApplicationState'] == 3 or r['ApplicationState'] == 131

initialized = r['ApplicationState'] == 129

**Comment by TimErps** [comment]
@stefangolas Should resolve it based on the code! Our Lynx is booked up all week, so my apologies for the delays in closing the loop on this for you!

**Comment by TimErps** [comment]
@stefangolas All good! Works now!
